use_frameworks!

platform :ios, '8.0'

target 'HeyRexNotificationLib_Example' do
  pod 'HeyRexNotificationLib', :path => '../'

  target 'HeyRexNotificationLib_Tests' do
    inherit! :search_paths

    
  end
end
